version: '3.7'

services:

  sample:
    container_name: frontend-user
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend-user'
      - '/frontend-user/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true